//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SOTIETKIEM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoTietKiem
    {
        public string MaSoTK { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string LoaiKyHan { get; set; }
        public Nullable<double> LaiSuat { get; set; }
        public Nullable<double> Sodu { get; set; }
        public Nullable<System.DateTime> NgayMS { get; set; }
        public Nullable<System.DateTime> NgayHH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
